# Generated by Django 3.2.23 on 2023-11-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_color_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='big_sale',
        ),
        migrations.CreateModel(
            name='ProductBig_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Product Big Sale',
                'verbose_name_plural': 'Product Big Sales',
                'ordering': ('product',),
            },
        ),
    ]
